// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC67_jole2TIP384XzzDr6Pn1UJjrdy85U',
    appId: '1:508921086278:web:161e108e60c5203ac2a547',
    messagingSenderId: '508921086278',
    projectId: 'cmts-3faa2',
    authDomain: 'cmts-3faa2.firebaseapp.com',
    storageBucket: 'cmts-3faa2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMykg9mN90m5bflDRLzK-Rol5OMY0dpG8',
    appId: '1:508921086278:android:f7d7ef0322844942c2a547',
    messagingSenderId: '508921086278',
    projectId: 'cmts-3faa2',
    storageBucket: 'cmts-3faa2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy4p_6n1d6yv5zGpaVcdON-tg35hn4wzc',
    appId: '1:508921086278:ios:3f37f2264e710716c2a547',
    messagingSenderId: '508921086278',
    projectId: 'cmts-3faa2',
    storageBucket: 'cmts-3faa2.appspot.com',
    iosBundleId: 'com.example.fleetCar',
  );
}
